config/routes.rb
Rails.application.routes.draw do



  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
 resources :articles do
   resources :comments
 end
  #root "articles#index"
  get "/categories/about" => "categories#about", as: :category_about


  #get "/articles/:id/archive" => "articles#archive", as: :article_archive
  get "/categories/category_id" => "categories#category", as: :category


  get "/" => "home#top"

  post "/upload_video" => "upload#upload_video", :as => :upload_video
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/

  post "/upload_image" => "upload#upload_image", :as => :upload_image

  post "/upload_file" => "upload#upload_file", :as => :upload_file

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

  attachment :image

  belongs_to :category
  
  has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  layout 'blog_application'
  #before_action :archives
  PER = 18





  def index
      @articles = Article.order(created_at: :desc).page(params[:page]).per(PER)
  end

  def show
    @comments = @article.comments
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save!
      redirect_to articles_path, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path, notice: '更新できました'
    else
      render :edit, alert: '更新できませんでした。'
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path, notice: '削除に成功しました。'
    else
      redirect_to articles_path, alert: '削除できませんでした'
    end
  end

#  def archive
#  @archives = Article.where(id: params[:id]).order(created_at: :desc).page(params[:page]).per(PER)
#  end



  private

  def find_article
    @article = Article.find(params[:id])
  end

  #def archives
  #  @articles = Article.all
  #  @article_months = @articles.group_by { |t| t.created_at.beginning_of_month}
  #end


  def article_params
    params.require(:article).permit(:title, :body, :image, :category_id)
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper


end

app/views/articles/_form.html.erb
 <!--<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@3.0.0-beta.1//js/froala_editor.pkgd.min.js"></script>-->
<%= form_for article do |f| %>
  <div class="form-group padding-15" id="cover_image">
    <%= image_tag 'grey-bg.jpg', class: 'img-responsive article-image relative'%>
    <i class="fa fa-camera camera-font" aria-hidden="true" style="font-size:50px "></i>

  </div>

  <%= f.attachment_field :image %>


<div class="form-group padding-15">
  <%= f.label :category_id, 'カテゴリー' %><br>
  <%=f.collection_select :category_id, Category.all, :id, :category_name%>

</div>
<div class="form-group　padding-15">
  <%= f.label :title, 'タイトル' %>
  <%=f.text_field :title, class: 'form-control', placeholder: 'タイトルを入力してください' %>
</div>
<div class="form-group">
  <%= f.label :body, '本文' %>
  <textarea rows="10" class="form-control" name="article[body]" id="edit" style="display: none;"></textarea>
</div>
<%=f.submit class: 'btn btn-success'%>
<%end%>
<!-- Include external JS libs. -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js"></script>

<!-- Include Editor JS files. -->
<!--<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/js/froala_editor.pkgd.min.js"></script>-->

<!-- Initialize the editor. -->
    <script>
    new FroalaEditor('#edit', {
      // Set the image upload URL.
      imageUploadURL: '/upload_image',

      imageUploadParams: {
        id: 'my_editor'
      }
    })
  </script>
  <script>
    new FroalaEditor('#edit', {
      // Set the video upload URL.
      videoUploadURL: '/upload_video',

      videoUploadParams: {
        id: 'my_editor'
      }
    })
  </script>
<script>
  new FroalaEditor('#edit', {
    // Set the file upload URL.
    fileUploadURL: '/upload_file',

    fileUploadParams: {
      id: 'my_editor'
    }
  })
</script>

app/views/articles/archive.html.erb
<!--<div class="title-color">
  <h1 class="text-center" style="margin:0; padding:10px; width:100% ">Top</h1>
</div>
<div class="container">
  <div class="row">
    <% @archives.each do |article| %>
      <%= link_to article do %>
        <div class="col-md-4 margin-top-5">
          <div class="bg-white">
            <% if article.image_id.present?%>
            <%= image_tag attachment_url(article, :image), class: 'img-responsive article-list-image', align: "left"%>
            <%else%>
            <%= image_tag '1.jpg', class: 'img-responsive article-list-image' %>
            <%end%>
            <div class="padding-bottom-15">
              <p class="title"><%= article.title %></p>
              <%if article.category.present?%>
              <p class="text-center"><span class="badge badge-secondary">#<%=article.category.category_name%></span></p>
              <%end%>
              <span class="time-left"><%= article.created_at.strftime("%Y年%m月%d日") %></span>
            </div>
          </div>
        </div>
        <%end%>
    <%end%>
  </div>
  <%= paginate @archives, class: 'font-size-30'%>


</div>-->

app/views/articles/edit.html.erb
<div class="container">
  <div class="col-md-12 margin-top-5 ">
    <div class="bg-white padding-15">
      <div class="text-center">
        <h1>ブログの編集</h1>
      </div>
          
      <div class="padding-bottom-15">
            <%= render 'form',article: @article%>
      </div>
     </div>
    </div>
  </div>

app/views/articles/index.html.erb
<h1 class="text-center font-family1" style="margin:0; padding:10px; width:100% ">Top</h1>
<div class="container">
  <div class="row">

    <% @articles.each do |article | %>
      <%= link_to article do %>
        <div class="col-md-4 margin-top-5">
          <div class="bg-white">
            <% if article.image_id.present?%>
            <%= image_tag attachment_url(article, :image), class: 'img-responsive article-list-image', align: "left"%>
            <%else%>
            <%= image_tag '1.jpg', class: 'img-responsive article-list-image' %>
            <%end%>
            <div class="padding-bottom-15">
              <p class="title"><%= article.title %></p>
                <%if article.category.present?%>
                <p class="text-center padding-top-10 padding-bottom-10"><span class="badge badge-secondary">#<%=article.category.category_name%></span></p>
                <%end%>
                <span class="time-left"><%= article.created_at.strftime("%Y年%m月%d日") %></span>
            </div>
          </div>
        </div>
        <%end%>
    <%end%>
  </div>
  <%= paginate @articles , class: 'font-size-30'%>
  <!--<div class="row">
      <%= link_to "新規作成", new_article_path, class: 'margin-top-5 btn btn-primary' %>
  </div> -->

</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="col-md-12 margin-top-5 ">
    <div class="bg-white padding-15">
      <div class="text-center">
        <h1>ブログの新規作成</h1>
      </div>

      <div class="padding-bottom-15">
            <%= render 'form',article: @article%>
      </div>
     </div>
    </div>
  </div>

app/views/articles/show.html.erb
<div class="container">
      <div class="col-md-12 margin-top-5 ">
        <div class="<!--bg-white--> padding-15">
          <!--<%= image_tag '1.jpg', class: 'article-image' %>-->
          <% if @article.image_id.present?%>
          <%= image_tag attachment_url(@article, :image), class: 'article-image' %>
          <%else%>
          <%= image_tag '1.jpg', class: 'article-image' %>
          <%end%>
          <h1 class="padding-15 font-size-30"><%=@article.title%></h1>
          <div class="padding-bottom-15">
            <p class="title"><%= @article.body.html_safe %></p>
            <%if @article.category.present?%>
            <p class="text-left"><span class="badge badge-secondary">#<%=@article.category.category_name%></span></p>
            <%end%>
            <p class="text-right">
              <%= @article.created_at.strftime("%Y年%m月%d日") %>
            </p>
          </div>
          <% if current_user.try(:admin?) %>
          <%= link_to '編集', edit_article_path(@article), class: 'btn btn-primary'%>
          <%= link_to '削除', article_path(@article), method: :delete, data: {confirm: '削除してもよろしいですか？'}, class: 'btn btn-danger'%>
          <%end%>
        </div>
      </div>
      <div class="comment-field col-md-12">
        <h2 class="text-left padding-bottom-15 " style="padding-left:20;">コメント欄</h2>

          <% @article.comments.each do |comment|%>

              <div class="padding-bottom-15 text-left">
                <p>#<%= comment.user.name%></p>
                  <p class="margin-15"><%= comment.content%></p>
                  <p class="border-1 padding-15"> </p>
              </div>
              <% if comment.user == current_user%>
                <%= link_to "コメントを削除する", article_comment_path(comment.article_id, comment.id), method: :delete, class: 'btn btn-danger' %>
              <%end%>
          <%end%>

          <% if current_user%>
            <%= form_for ([@article, @article.comments.build]) do |f|%>
              <div class="form-group　padding-15">
                <p>
                  <%= f.label :content, "コメントを入力する"%>
                  <%= f.text_area :content, class: 'form-control padding-15 margin-15' ,placeholder: 'コメントを入力する' %>
                </p>
              </div>
              <%= f.submit class: 'btn btn-success margin-15'%>
            <%end%>
            <%else%>
            <p>アカウントがログインされているとコメントが出来るにようになります。</p>
          <%end%>
      </div>
</div>