config/routes.rb
Rails.application.routes.draw do



  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
 resources :articles do
   resources :comments
 end
  #root "articles#index"
  get "/categories/about" => "categories#about", as: :category_about


  #get "/articles/:id/archive" => "articles#archive", as: :article_archive
  get "/categories/category_id" => "categories#category", as: :category


  get "/" => "home#top"

  post "/upload_video" => "upload#upload_video", :as => :upload_video
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/

  post "/upload_image" => "upload#upload_image", :as => :upload_image

  post "/upload_file" => "upload#upload_file", :as => :upload_file

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="display-inline-block width-50">

  </div>
  <div class="display-inline-block width-50">
    <div class="form-group">
      <div class="form-control">

      </div>
    </div>
    <div class="form-group">
      <div class="form-control">

      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div id="blog_header_top">
    <p class="notice alert-dark"><%= notice %></p>
    <p class="alert alert-primary"><%= alert %></p>
    <ul class="blog_header_ul">
      <li><%=link_to("HOME","/")%></li>
      <!--<li><%=link_to("広場","/")%></li>-->
    </ul>
    <i class="fa fa-bars" aria-hidden="true"></i>
    <div class="clear_left"></div>


  <div id="blog_header_main" class="container text-center">
    <div class="blog_sentence">
      <h1 class="text-center font-size-30 margin-top-40">暇を持て余した<br class="title-br">神々の嘆きブログ</h1>
    </div>

   <div class="margin-top-1" id="navbarSupportedContent">
       <ul class="text-center">
         <li class="li-1 color-white">
           <%= link_to "TOP", articles_path, class: "nav-link active" %>
         </li>
         <li class="li-1 color-white">
           <%= link_to "ABOUT", category_about_path%>
         </li>
         <li class="li-1 dropdown color-white">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CATEGORY<span class="caret"></span></a>
           <ul class="dropdown-menu color-black">
            <li><%=link_to "勉強", category_path(category_id: 1) %></li>
            <li><%=link_to "筋トレ", category_path(category_id: 3)%></li>
            <!--<li role="separator" class="divider"></li>-->
            <!--<li class="dropdown-header">header</li>-->
            <li><%= link_to "その他", category_path(category_id: 2)%></li>
            <li><%= link_to "健康", category_path(category_id: 4)%></li>
          </ul>
         </li>
         <% if current_user.try(:admin?) %>
         <li class="li-1 color-white"><%= link_to "NEW ARTICLE", new_article_path, class: "nav-link" %></li>
         <li class="li-1 color-white"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
         <%elsif current_user%>
         <li class="li-1 color-white"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
         <%else%>
         <li class="li-1 color-white"><%= link_to "CREATE ACCOUNT", new_user_registration_path, class: "nav-link" %></li>
         <li class="li-1 color-white"><%= link_to "LOGIN", new_user_session_path, class: "nav-link" %></li>
         <%end%>
       </ul>
       <div class="clear_left"></div>
    </div>
  <div id="nav-drawer">
      <input id="nav-input" type="checkbox" class="nav-unshown">
      <label id="nav-open" for="nav-input"><span></span></label>
      <label class="nav-unshown" id="nav-close" for="nav-input"></label>
      <div id="nav-content">
        <div class="margin-top-1" id="navbarSupportedContent1">
            <ul class="text-left">
              <li class="color-white padding-bottom-15">
                <%= link_to "TOP", articles_path, class: "nav-link active" %>
              </li>
              <li class="color-white padding-bottom-15">
                <%= link_to "ABOUT", category_about_path%>
              </li>
              <li class="dropdown color-white padding-bottom-15">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CATEGORY<span class="caret"></span></a>
                <ul class="dropdown-menu color-black">
                 <li><%=link_to "勉強", category_path(category_id: 1) %></li>
                 <li><%=link_to "筋トレ", category_path(category_id: 3)%></li>
                 <!--<li role="separator" class="divider"></li>-->
                 <!--<li class="dropdown-header">header</li>-->
                 <li><%= link_to "その他", category_path(category_id: 2)%></li>
                 <li><%= link_to "健康", category_path(category_id: 4)%></li>
               </ul>
              </li>
              <% if current_user.try(:admin?) %>
              <li class="color-white padding-bottom-15"><%= link_to "NEW ARTICLE", new_article_path, class: "nav-link" %></li>
              <li class="color-white padding-bottom-15"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
              <%elsif current_user%>
              <li class="color-white padding-bottom-15"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
              <%else%>
              <li class="color-white padding-bottom-15"><%= link_to "CREATE ACCOUNT", new_user_registration_path, class: "nav-link" %></li>
              <li class="color-white padding-bottom-15"><%= link_to "LOGIN", new_user_session_path, class: "nav-link" %></li>
              <%end%>
            </ul>
            <div class="clear_left"></div>
         </div>
      </div>
  </div>
    </div>
  </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">

 <!-- Include Editor style. -->
 <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
 <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_style.min.css" rel="stylesheet" type="text/css" />
  </head>

  <body>
  <!--   <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>-->

      <%= render 'layouts/header'%>
    <div id="blog_area" class="container">

      <div id="blog_index" class="">
    <%= yield %>
      </div>
      <div class="clear_both"></div>
    </div>
  </body>
</html>

app/views/layouts/blog_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SLOTHLIFEBLOG</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
    <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />

    <!-- Include Editor style. -->
<!--    <link href="https://cdn.jsdelivr.net/npm/froala-editor@3.0.0-beta.1/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />-->

  <!--  <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />-->
    <!--<link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_style.min.css" rel="stylesheet" type="text/css" />-->
  </head>

  <body>
    <!-- Include Editor JS files. -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/js/froala_editor.pkgd.min.js"></script>
      <%= render 'layouts/header'%>
    <div id="blog_area" class="container">
      <div id="blog_index">
    <%= yield %>
      </div>
      <div class="clear_both"></div>
    </div>
    <div id="blog_footer" style="height:300px; background-color:#778899">
      <%= render 'layouts/footer',article_months: @article_months%>
    </div>
  </body>
</html>

app/views/layouts/home_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SLOTHLIFE</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-main">
          <div class="header-link-list">
            <ul class="header-link">
              <li><%= link_to 'Home', "/", id: 'home_top'%></li>
              <li><%= link_to "Profile", "#profile_page"%></li>
              <li><%= link_to "ブログ", articles_path%></li>
              <li>お問い合わせ</li>
            </ul>
          </div>

        </div>
      </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/login_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">

 <!-- Include Editor style. -->
 <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
 <link href="https://cdn.jsdelivr.net/npm/froala-editor@2.9.5/css/froala_style.min.css" rel="stylesheet" type="text/css" />
  </head>

  <body>

<div class="bg-login">
    <div id="blog_area" class="container">

      <div id="blog_index" class="">
    <%= yield %>
      </div>
      <div class="clear_both"></div>
    </div>
</div>
  </body>
</html>